buildlimit: 1
instlimit: 100000
memlimit: 512
path:
  compiler: /ClionProjects/Comlier-Mx_star/cmake-build-debug/Complier-Mx_star
  dataset: /ClionProjects/Comlier-Mx_star/testcase
stage: semantic
timelimit: 15
